// SkyClaw App - JavaScript
// =========================================

// DOM Elements
const form = document.getElementById('personalForm');

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    console.log('SkyClaw App initialized');
});

// Form Submission
form.addEventListener('submit', async (e) => {
    e.preventDefault();
    
    const submitBtn = form.querySelector('button[type="submit"]');
    submitBtn.classList.add('loading');
    
    try {
        // Collect form data
        const formData = new FormData(form);
        const data = Object.fromEntries(formData.entries());
        
        // Get export format
        data.exportFormat = form.querySelector('input[name="exportFormat"]:checked').value;
        
        console.log('Form data:', data);
        
        // Generate file based on format
        if (data.exportFormat === 'pdf') {
            await generatePDF(data);
        } else if (data.exportFormat === 'docx') {
            await generateDOCX(data);
        }
        
        showToast('Xuất file thành công!', 'success');
    } catch (error) {
        console.error('Error:', error);
        showToast('Có lỗi xảy ra: ' + error.message, 'error');
    } finally {
        submitBtn.classList.remove('loading');
    }
});

// Reset Form
function resetForm() {
    form.reset();
    showToast('Đã nhập lại form', 'success');
}

// Generate PDF
async function generatePDF(data) {
    // Using jsPDF library
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // Colors
    const primaryColor = [99, 102, 241];
    const textColor = [30, 41, 59];
    const mutedColor = [100, 116, 139];
    
    // Header
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('THÔNG TIN CÁ NHÂN', 105, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('SkyClaw - Personal Information Form', 105, 30, { align: 'center' });
    
    let y = 55;
    
    // Section 1: Basic Info
    doc.setTextColor(...textColor);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('I. THÔNG TIN CƠ BẢN', 20, y);
    y += 10;
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const basicFields = [
        ['Họ và tên:', data.fullName || 'N/A'],
        ['Ngày sinh:', data.dateOfBirth || 'N/A'],
        ['Giới tính:', data.gender === 'male' ? 'Nam' : data.gender === 'female' ? 'Nữ' : data.gender === 'other' ? 'Khác' : 'N/A'],
        ['Quốc tịch:', data.nationality || 'N/A']
    ];
    
    basicFields.forEach(([label, value]) => {
        doc.setTextColor(...mutedColor);
        doc.text(label, 25, y);
        doc.setTextColor(...textColor);
        doc.text(value, 80, y);
        y += 8;
    });
    
    y += 10;
    
    // Section 2: Contact Info
    doc.setTextColor(...textColor);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('II. THÔNG TIN LIÊN LẠC', 20, y);
    y += 10;
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const contactFields = [
        ['Email:', data.email || 'N/A'],
        ['Số điện thoại:', data.phone || 'N/A'],
        ['Địa chỉ:', data.address || 'N/A']
    ];
    
    contactFields.forEach(([label, value]) => {
        doc.setTextColor(...mutedColor);
        doc.text(label, 25, y);
        doc.setTextColor(...textColor);
        doc.text(value, 80, y);
        y += 8;
    });
    
    y += 10;
    
    // Section 3: Other Info
    doc.setTextColor(...textColor);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('III. THÔNG TIN CÁ NHÂN KHÁC', 20, y);
    y += 10;
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const otherFields = [
        ['Số CMND/CCCD:', data.idNumber || 'N/A'],
        ['Ngày cấp:', data.issueDate || 'N/A'],
        ['Nơi cấp:', data.issuePlace || 'N/A'],
        ['Nghề nghiệp:', data.occupation || 'N/A'],
        ['Nơi làm việc:', data.workplace || 'N/A']
    ];
    
    otherFields.forEach(([label, value]) => {
        doc.setTextColor(...mutedColor);
        doc.text(label, 25, y);
        doc.setTextColor(...textColor);
        doc.text(value, 80, y);
        y += 8;
    });
    
    // Footer
    doc.setTextColor(...mutedColor);
    doc.setFontSize(9);
    doc.text(`Ngày xuất: ${new Date().toLocaleDateString('vi-VN')}`, 20, 285);
    doc.text('Generated by SkyClaw', 105, 285, { align: 'center' });
    
    // Save
    doc.save(`thong_tin_ca_nhan_${Date.now()}.pdf`);
}

// Generate DOCX
async function generateDOCX(data) {
    // Check if docx library is loaded
    if (typeof window.docx === 'undefined') {
        throw new Error('Thư viện docx chưa được tải. Vui lòng tải lại trang.');
    }
    
    // Access docx classes directly from window.docx
    const Document = window.docx.Document;
    const Packer = window.docx.Packer;
    const Paragraph = window.docx.Paragraph;
    const TextRun = window.docx.TextRun;
    const HeadingLevel = window.docx.HeadingLevel;
    const AlignmentType = window.docx.AlignmentType;
    const Table = window.docx.Table;
    const TableRow = window.docx.TableRow;
    const TableCell = window.docx.TableCell;
    const WidthType = window.docx.WidthType;
    
    // Verify all required classes are available
    if (!Document || !Packer || !Paragraph || !TextRun) {
        throw new Error('Thư viện docx chưa được tải đầy đủ. Vui lòng tải lại trang.');
    }
    
    // Create document
    const doc = new Document({
        sections: [{
            properties: {},
            children: [
                // Title
                new Paragraph({
                    text: 'THÔNG TIN CÁ NHÂN',
                    heading: HeadingLevel.HEADING_1,
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 200 }
                }),
                
                new Paragraph({
                    text: 'SkyClaw - Personal Information Form',
                    alignment: AlignmentType.CENTER,
                    spacing: { after: 400 }
                }),
                
                // Section 1
                new Paragraph({
                    text: 'I. THÔNG TIN CƠ BẢN',
                    heading: HeadingLevel.HEADING_2,
                    spacing: { before: 400, after: 200 }
                }),
                
                createTable([
                    ['Họ và tên:', data.fullName || 'N/A'],
                    ['Ngày sinh:', data.dateOfBirth || 'N/A'],
                    ['Giới tính:', data.gender === 'male' ? 'Nam' : data.gender === 'female' ? 'Nữ' : data.gender === 'other' ? 'Khác' : 'N/A'],
                    ['Quốc tịch:', data.nationality || 'N/A']
                ]),
                
                // Section 2
                new Paragraph({
                    text: 'II. THÔNG TIN LIÊN LẠC',
                    heading: HeadingLevel.HEADING_2,
                    spacing: { before: 400, after: 200 }
                }),
                
                createTable([
                    ['Email:', data.email || 'N/A'],
                    ['Số điện thoại:', data.phone || 'N/A'],
                    ['Địa chỉ:', data.address || 'N/A']
                ]),
                
                // Section 3
                new Paragraph({
                    text: 'III. THÔNG TIN CÁ NHÂN KHÁC',
                    heading: HeadingLevel.HEADING_2,
                    spacing: { before: 400, after: 200 }
                }),
                
                createTable([
                    ['Số CMND/CCCD:', data.idNumber || 'N/A'],
                    ['Ngày cấp:', data.issueDate || 'N/A'],
                    ['Nơi cấp:', data.issuePlace || 'N/A'],
                    ['Nghề nghiệp:', data.occupation || 'N/A'],
                    ['Nơi làm việc:', data.workplace || 'N/A']
                ]),
                
                // Footer
                new Paragraph({
                    children: [
                        new TextRun({ 
                            text: `Ngày xuất: ${new Date().toLocaleDateString('vi-VN')}`,
                            size: 20,
                            color: '666666'
                        })
                    ],
                    spacing: { before: 400 }
                })
            ]
        }]
    });
    
    // Save
    const blob = await Packer.toBlob(doc);
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `thong_tin_ca_nhan_${Date.now()}.docx`;
    a.click();
    URL.revokeObjectURL(url);
}

// Helper: Create table
function createTable(rows) {
    const Table = window.docx.Table;
    const TableRow = window.docx.TableRow;
    const TableCell = window.docx.TableCell;
    const Paragraph = window.docx.Paragraph;
    const TextRun = window.docx.TextRun;
    const WidthType = window.docx.WidthType;
    
    return new Table({
        rows: rows.map(([label, value]) => 
            new TableRow({
                children: [
                    new TableCell({
                        children: [new Paragraph({
                            children: [new TextRun({ text: label, bold: true })]
                        })],
                        shading: { fill: 'F8FAFC' }
                    }),
                    new TableCell({
                        children: [new Paragraph(value || 'N/A')]
                    })
                ]
            })
        ),
        width: { size: 100, type: WidthType.PERCENTAGE }
    });
}

// Show Toast
function showToast(message, type = 'success') {
    const existingToast = document.querySelector('.toast');
    if (existingToast) {
        existingToast.remove();
    }
    
    const toast = document.createElement('div');
    toast.className = `toast ${type}`;
    toast.innerHTML = `
        ${type === 'success' 
            ? '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>'
            : '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/></svg>'
        }
        <span>${message}</span>
    `;
    
    document.body.appendChild(toast);
    
    // Trigger animation
    setTimeout(() => {
        toast.classList.add('show');
    }, 10);
    
    // Remove after 3 seconds
    setTimeout(() => {
        toast.classList.remove('show');
        setTimeout(() => toast.remove(), 300);
    }, 3000);
}

// Export functions to global scope
window.resetForm = resetForm;
window.generatePDF = generatePDF;
window.generateDOCX = generateDOCX;